package proyecto_ad_hibernate;
// Generated 20-ene-2020 12:37:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private String nombreCliente;
     private String reserva;
     private String alergico;
     private int costeDeLaComida;
     private Set restaurantes = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String nombreCliente, String reserva, String alergico, int costeDeLaComida) {
        this.nombreCliente = nombreCliente;
        this.reserva = reserva;
        this.alergico = alergico;
        this.costeDeLaComida = costeDeLaComida;
    }
    public Cliente(String nombreCliente, String reserva, String alergico, int costeDeLaComida, Set restaurantes) {
       this.nombreCliente = nombreCliente;
       this.reserva = reserva;
       this.alergico = alergico;
       this.costeDeLaComida = costeDeLaComida;
       this.restaurantes = restaurantes;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public String getReserva() {
        return this.reserva;
    }
    
    public void setReserva(String reserva) {
        this.reserva = reserva;
    }
    public String getAlergico() {
        return this.alergico;
    }
    
    public void setAlergico(String alergico) {
        this.alergico = alergico;
    }
    public int getCosteDeLaComida() {
        return this.costeDeLaComida;
    }
    
    public void setCosteDeLaComida(int costeDeLaComida) {
        this.costeDeLaComida = costeDeLaComida;
    }
    public Set getRestaurantes() {
        return this.restaurantes;
    }
    
    public void setRestaurantes(Set restaurantes) {
        this.restaurantes = restaurantes;
    }




}


