package proyecto_ad_hibernate;
// Generated 20-ene-2020 12:37:15 by Hibernate Tools 4.3.1



/**
 * Cocinero generated by hbm2java
 */
public class Cocinero  implements java.io.Serializable {


     private Integer idcocinero;
     private Plato plato;
     private double salario;
     private String nombreCocinero;
     private String espcialidad;
     private int numeroDePremios;

    public Cocinero() {
    }

    public Cocinero(Plato plato, double salario, String nombreCocinero, String espcialidad, int numeroDePremios) {
       this.plato = plato;
       this.salario = salario;
       this.nombreCocinero = nombreCocinero;
       this.espcialidad = espcialidad;
       this.numeroDePremios = numeroDePremios;
       
    }
   
    public Integer getIdcocinero() {
        return this.idcocinero;
    }
    
    public void setIdcocinero(Integer idcocinero) {
        this.idcocinero = idcocinero;
    }
    public Plato getPlato() {
        return this.plato;
    }
    
    public void setPlato(Plato plato) {
        this.plato = plato;
    }
    public double getSalario() {
        return this.salario;
    }
    
    public void setSalario(double salario) {
        this.salario = salario;
    }
    public String getNombreCocinero() {
        return this.nombreCocinero;
    }
    
    public void setNombreCocinero(String nombreCocinero) {
        this.nombreCocinero = nombreCocinero;
    }
    public String getEspcialidad() {
        return this.espcialidad;
    }
    
    public void setEspcialidad(String espcialidad) {
        this.espcialidad = espcialidad;
    }
    public int getNumeroDePremios() {
        return this.numeroDePremios;
    }
    
    public void setNumeroDePremios(int numeroDePremios) {
        this.numeroDePremios = numeroDePremios;
    }




}


