package proyecto_ad_hibernate;
// Generated 20-ene-2020 12:37:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Restaurante generated by hbm2java
 */
public class Restaurante  implements java.io.Serializable {


     private Integer idrestaurante;
     private Cliente cliente;
     private String nombreRestaurante;
     private String direccionRestaurante;
     private String aforoMaximoRestaurante;
     private int numeroEmpleadosRestaurante;
     private Set platos = new HashSet(0);

    public Restaurante() {
    }

	
    public Restaurante(Cliente cliente, String nombreRestaurante, String direccionRestaurante, String aforoMaximoRestaurante, int numeroEmpleadosRestaurante) {
        this.cliente = cliente;
        this.nombreRestaurante = nombreRestaurante;
        this.direccionRestaurante = direccionRestaurante;
        this.aforoMaximoRestaurante = aforoMaximoRestaurante;
        this.numeroEmpleadosRestaurante = numeroEmpleadosRestaurante;
    }
    public Restaurante(Cliente cliente, String nombreRestaurante, String direccionRestaurante, String aforoMaximoRestaurante, int numeroEmpleadosRestaurante, Set platos) {
       this.cliente = cliente;
       this.nombreRestaurante = nombreRestaurante;
       this.direccionRestaurante = direccionRestaurante;
       this.aforoMaximoRestaurante = aforoMaximoRestaurante;
       this.numeroEmpleadosRestaurante = numeroEmpleadosRestaurante;
       this.platos = platos;
    }
   
    public Integer getIdrestaurante() {
        return this.idrestaurante;
    }
    
    public void setIdrestaurante(Integer idrestaurante) {
        this.idrestaurante = idrestaurante;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getNombreRestaurante() {
        return this.nombreRestaurante;
    }
    
    public void setNombreRestaurante(String nombreRestaurante) {
        this.nombreRestaurante = nombreRestaurante;
    }
    public String getDireccionRestaurante() {
        return this.direccionRestaurante;
    }
    
    public void setDireccionRestaurante(String direccionRestaurante) {
        this.direccionRestaurante = direccionRestaurante;
    }
    public String getAforoMaximoRestaurante() {
        return this.aforoMaximoRestaurante;
    }
    
    public void setAforoMaximoRestaurante(String aforoMaximoRestaurante) {
        this.aforoMaximoRestaurante = aforoMaximoRestaurante;
    }
    public int getNumeroEmpleadosRestaurante() {
        return this.numeroEmpleadosRestaurante;
    }
    
    public void setNumeroEmpleadosRestaurante(int numeroEmpleadosRestaurante) {
        this.numeroEmpleadosRestaurante = numeroEmpleadosRestaurante;
    }
    public Set getPlatos() {
        return this.platos;
    }
    
    public void setPlatos(Set platos) {
        this.platos = platos;
    }




}


